### ISSUE TITLE
Correctly handle OAuth Exceptions

### ISSUE THREAD

**Issue by burnedikt** [Innoactive/Hub-Base-Asset-Pipeline#4]
Currently, OAuth Exceptions are not handled in any way by the application. Different types of Exceptions exist and should provide more detailed feedback to the user, e.g.:

# Invalid Client

```
pdf-pipeline | Traceback (most recent call last):
pdf-pipeline |   File "command_line.py", line 17, in <module>
pdf-pipeline |     main()
pdf-pipeline |   File "command_line.py", line 11, in main
pdf-pipeline |     config=config
pdf-pipeline |   File "/src/pdf_pipeline.py", line 34, in __init__
pdf-pipeline |     super(PdfAssetPipeline, self).__init__(config=config, *args, **kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/pipeline.py", line 135, in __init__
pdf-pipeline |     self.client = get_client_for_config(config)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 265, in get_client_for_config
pdf-pipeline |     return client_factory.client
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 129, in client
pdf-pipeline |     client = self.get_legacy_application_client()
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 167, in get_legacy_application_client
pdf-pipeline |     oauth.fetch_token(self.token_url, username=self.username, password=self.password, **extra_kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
pdf-pipeline |     self._client.parse_request_body_response(r.text, scope=self.scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 408, in parse_request_body_response
pdf-pipeline |     self.token = parse_token_response(body, scope=scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
pdf-pipeline |     validate_token_parameters(params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
pdf-pipeline |     raise_from_error(params.get('error'), params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
pdf-pipeline |     raise cls(**kwargs)
pdf-pipeline | oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client)
pdf-pipeline exited with code 1
```

--> Instead of showing the error dump, should show a descriptive message about the used client credentials being invalid

# Unauthorized Client

```
pdf-pipeline | Traceback (most recent call last):
pdf-pipeline |   File "command_line.py", line 17, in <module>
pdf-pipeline |     main()
pdf-pipeline |   File "command_line.py", line 11, in main
pdf-pipeline |     config=config
pdf-pipeline |   File "/src/pdf_pipeline.py", line 34, in __init__
pdf-pipeline |     super(PdfAssetPipeline, self).__init__(config=config, *args, **kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/pipeline.py", line 135, in __init__
pdf-pipeline |     self.client = get_client_for_config(config)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 265, in get_client_for_config
pdf-pipeline |     return client_factory.client
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 129, in client
pdf-pipeline |     client = self.get_legacy_application_client()
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 167, in get_legacy_application_client
pdf-pipeline |     oauth.fetch_token(self.token_url, username=self.username, password=self.password, **extra_kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
pdf-pipeline |     self._client.parse_request_body_response(r.text, scope=self.scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 408, in parse_request_body_response
pdf-pipeline |     self.token = parse_token_response(body, scope=scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
pdf-pipeline |     validate_token_parameters(params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
pdf-pipeline |     raise_from_error(params.get('error'), params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
pdf-pipeline |     raise cls(**kwargs)
pdf-pipeline | oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client)
pdf-pipeline exited with code 1
```

--> Instead of showing the error dump, should show a descriptive message about the used client credentials are valid but the client is not authorized to use the selected grant type (e.g. password flow)

# Invalid Grant (Username / Password)

```
pdf-pipeline | Traceback (most recent call last):
pdf-pipeline |   File "command_line.py", line 17, in <module>
pdf-pipeline |     main()
pdf-pipeline |   File "command_line.py", line 11, in main
pdf-pipeline |     config=config
pdf-pipeline |   File "/src/pdf_pipeline.py", line 34, in __init__
pdf-pipeline |     super(PdfAssetPipeline, self).__init__(config=config, *args, **kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/pipeline.py", line 135, in __init__
pdf-pipeline |     self.client = get_client_for_config(config)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 265, in get_client_for_config
pdf-pipeline |     return client_factory.client
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 129, in client
pdf-pipeline |     client = self.get_legacy_application_client()
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 167, in get_legacy_application_client
pdf-pipeline |     oauth.fetch_token(self.token_url, username=self.username, password=self.password, **extra_kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
pdf-pipeline |     self._client.parse_request_body_response(r.text, scope=self.scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 408, in parse_request_body_response
pdf-pipeline |     self.token = parse_token_response(body, scope=scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
pdf-pipeline |     validate_token_parameters(params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
pdf-pipeline |     raise_from_error(params.get('error'), params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
pdf-pipeline |     raise cls(**kwargs)
pdf-pipeline | oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid credentials given.
pdf-pipeline exited with code 1
```

--> Instead of showing the error dump, should show a descriptive message indicating that the provided user credentials are invalid (password flow)

# Invalid Grant (Auth Code)

```
pdf-pipeline | Traceback (most recent call last):
pdf-pipeline |   File "command_line.py", line 17, in <module>
pdf-pipeline |     main()
pdf-pipeline |   File "command_line.py", line 11, in main
pdf-pipeline |     config=config
pdf-pipeline |   File "/src/pdf_pipeline.py", line 34, in __init__
pdf-pipeline |     super(PdfAssetPipeline, self).__init__(config=config, *args, **kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/pipeline.py", line 135, in __init__
pdf-pipeline |     self.client = get_client_for_config(config)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 265, in get_client_for_config
pdf-pipeline |     return client_factory.client
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 127, in client
pdf-pipeline |     client = self.get_mail_application_client()
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/asset_pipeline/client.py", line 148, in get_mail_application_client
pdf-pipeline |     oauth.fetch_token(self.token_url, authorization_response=self.oauth_code, **extra_kwargs)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
pdf-pipeline |     self._client.parse_request_body_response(r.text, scope=self.scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 408, in parse_request_body_response
pdf-pipeline |     self.token = parse_token_response(body, scope=scope)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
pdf-pipeline |     validate_token_parameters(params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
pdf-pipeline |     raise_from_error(params.get('error'), params)
pdf-pipeline |   File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
pdf-pipeline |     raise cls(**kwargs)
pdf-pipeline | oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)
```

--> Instead of showing the error dump, should show a descriptive message indicating that the provided  oauth_code is invalid (or already expired)

**Comment by burnedikt** [comment]
fixed with #5
